#version 460 core
layout(local_size_x=16,local_size_y=16,local_size_z=1)in;
layout(rgba32f,binding=0)uniform image2D image_in;
layout(rgba32f,binding=1)uniform image2D image_out;

void main()
{
    ivec2 dims=imageSize(image_in);
    if(gl_GlobalInvocationID.x>=dims.x||gl_GlobalInvocationID.y>=dims.y)
    return;
    ivec2 pixel_coords=ivec2(gl_GlobalInvocationID.xy);
    vec4 pixel=imageLoad(image_in,pixel_coords);
    imageStore(image_out,pixel_coords,pixel);
}